version: "3.8"
services:
  db:
    image: mysql:8
    container_name: mercadinho-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercadinho
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mercadinho-backend
    restart: always
    environment:
      DATABASE_URL: mysql://user:password@db:3306/mercadinho
    ports:
      - "4000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./mercadinho-frontend
      dockerfile: Dockerfile
    container_name: mercadinho-frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db_data:
